// Writes lib/engine-src.ts: a hash of every engine source file, for the engine fingerprint.
// The fingerprint hashes hook functions from the deployed bundle, which misses module-level
// helpers the hooks call; this build-time hash catches every engine edit. Run before a push:
//   node devtools/hash-engine.mjs
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const files = [];
(function walk(d) { for (const n of readdirSync(d).sort()) { const p = join(d, n); if (statSync(p).isDirectory()) walk(p); else if (/\.(ts|tsx|js)$/.test(n)) files.push(p); } })(join(root, 'engine'));
const h = createHash('sha256');
for (const f of files) h.update(f.slice(root.length)).update('\0').update(readFileSync(f)).update('\0');
const hash = h.digest('hex').slice(0, 12);
const out = `// Generated by devtools/hash-engine.mjs — a hash of engine/** at build time. Do not edit.\nexport const ENGINE_SRC_HASH = '${hash}';\nexport const ENGINE_SRC_FILES = ${files.length};\n`;
const path = join(root, 'lib', 'engine-src.ts');
let prev = '';
try { prev = readFileSync(path, 'utf8'); } catch { /* first run */ }
if (prev !== out) writeFileSync(path, out);
console.log(`${prev === out ? 'unchanged' : 'wrote'} lib/engine-src.ts: ${hash} (${files.length} files)`);
