export { buildSubstrateTile, resolveCrossing, resolveCrossingKind, sampleSubstrate } from './kernel';
export { resolveFluidContact } from './contact';
export {
  adaptHydroSample,
  sampleHydroContactLayers,
  type HydroAdapterOptions,
  type HydroContactLayers,
} from './hydro-adapter';
export {
  SubstrateShadowMonitor,
  type LegacyFluidObservation,
  type ShadowCrossingObservation,
  type SubstrateCutoverGate,
  type SubstrateShadowObservation,
  type SubstrateShadowSnapshot,
} from './shadow';
export {
  resolveProductionAlignedRoadProfile,
  resolveProductionEngineeredRoadProfile,
  resolveProductionRoadCrossSection,
  resolveProductionRoadHostPlane,
  resolveProductionRoadJunctionWarp,
  resolveProductionRoadStructureProfile,
  sampleProductionRoadHostPlane,
  type ProductionAlignedRoadProfile,
  type ProductionAlignedRoadProfileInput,
  type ProductionEngineeredRoadProfile,
  type ProductionEngineeredRoadProfileInput,
  type ProductionRoadCrossSection,
  type ProductionRoadCrossSectionInput,
  type ProductionRoadHostPlane,
  type ProductionRoadHostPlaneInput,
  type ProductionRoadJunctionWarp,
  type ProductionRoadJunctionWarpInput,
  type ProductionRoadStructureMode,
  type ProductionRoadStructureProfile,
  type ProductionRoadStructureProfileInput,
} from './road-profile';
export {
  buildProductionRoadSurfaceGeometry,
  resolveProductionRoadEndCrop,
  resolveProductionRoadKerbGeometry,
  smoothProductionRoadSurfaceNormals,
  type ProductionRoadCropHost,
  type ProductionRoadEndCrop,
  type ProductionRoadEndCropDecision,
  type ProductionRoadEndCropInput,
  type ProductionRoadEndCropReason,
  type ProductionRoadKerbGeometry,
  type ProductionRoadKerbGeometryInput,
  type ProductionRoadSurfaceBay,
  type ProductionRoadSurfaceCorner,
  type ProductionRoadSurfaceGeometry,
} from './road-surface';
export {
  pointInProductionCrossingFootprint,
  productionCrossingFootprint,
  ProductionCrossingRegistry,
  resolveProductionCrossing,
  resolveProductionCrossingIntent,
  navigableClearance,
  resolveProductionBridgeProfile,
  resolveProductionDeck,
  waterClearanceForClass,
  PRODUCTION_BRIDGE_CLEARANCE_M,
  PRODUCTION_BRIDGE_DECK_SAMPLE_STEP_M,
  PRODUCTION_BRIDGE_PORTAL_REACH_M,
  WET_CLEARANCE_MAX,
  WET_SPAN_RATIO,
  type CrossingAuthority,
  type DeckAuthority,
  type ProductionBridgeLiftSource,
  type ProductionBridgeProfileInput,
  type ProductionBridgeProfileResult,
  type ProductionDeckDecision,
  type ProductionDeckInput,
  type CrossingImplementation,
  type CrossingStructureOutcome,
  type ProductionCrossingEvidenceInput,
  type ProductionCrossingFootprint,
  type ProductionCrossingInput,
  type ProductionCrossingIntent,
  type ProductionCrossingKind,
  type ProductionCrossingRecord,
  type ProductionCrossingSnapshot,
} from './crossing-authority';
export {
  buildProductionSubstrateTile,
  findProductionDriveWaterOverlaps,
  ProductionSubstrateStore,
  sampleProductionSubstrateTile,
  type ProductionDriveSample,
  type ProductionDriveRenderMesh,
  type ProductionDriveSegment,
  type ProductionDriveWaterOverlap,
  type ProductionGroundMesh,
  type ProductionGroundSample,
  type ProductionHydroDetailCollider,
  type ProductionRenderAttribute,
  type ProductionRenderAttributeArray,
  type ProductionRenderGroup,
  type ProductionRenderMesh,
  type ProductionSubstrateLookup,
  type ProductionSubstrateStoreSnapshot,
  type ProductionSubstrateTile,
  type ProductionSubstrateTileInput,
  type ProductionWaterProbe,
  type ProductionWaterMotionSegment,
} from './production-tile';
export {
  SubstrateFallbackMonitor,
  type SubstrateContactConsumer,
  type SubstrateConsumerAvailability,
  type SubstrateFallbackSnapshot,
} from './availability';
export {
  resolveProductionSubstrateMode,
  type ProductionSubstrateMode,
  type ProductionSubstrateModeName,
} from './mode';
export { buildProductionHydroFixture } from './hydro-fixture';
export { makeCrossingFixture, type CrossingFixtureOptions } from './fixtures';
export {
  buildCulvertBoreGeometry,
  buildCulvertHeadwallGeometry,
  type CulvertBoreGeometry,
  type CulvertBoreInput,
  type CulvertHeadwallGeometry,
  type CulvertHeadwallInput,
  type CulvertStructureFamily,
} from './culvert-detail';
export {
  appendProductionRoadArch,
  appendProductionRoadFace,
  appendProductionRoadPier,
  appendProductionRoadQuad,
  appendProductionRoadRail,
  appendProductionRoadSign,
  appendProductionRoadStud,
  type ProductionRoadArchInput,
  type ProductionRoadFaceInput,
  type ProductionRoadPierInput,
  type ProductionRoadRailInput,
  type ProductionRoadSignInput,
  type ProductionRoadSignResult,
  type ProductionRoadStudInput,
} from './road-structure';
export {
  appendProductionRoadBatter,
  resolveProductionRoadBatterReach,
  type ProductionRoadBatterColour,
  type ProductionRoadBatterInput,
  type ProductionRoadBatterReachInput,
  type ProductionRoadBatterReachResult,
  type ProductionRoadBatterResult,
  type ProductionRoadBatterStep,
  type ProductionRoadBatterTint,
} from './road-batter';
export {
  box as appendProductionBridgeBox,
  bridgeAxis,
  buildBridgeForms,
  planBridgeStations,
  specFor as productionBridgeFormSpec,
  strand as appendProductionBridgeStrand,
  tower as appendProductionBridgeTower,
  type ArchPlace,
  type BridgeAxis,
  type BridgeForm,
  type BridgeFormSpec,
  type BridgeMesh,
  type BridgeWay,
  type CablePattern,
  type DeckKind,
  type EndFeature,
  type Station as BridgeStation,
  type TowerBuilt,
  type TowerStyle,
  type TrussPlace,
} from './bridge-forms';
export {
  buildRapidDetailField,
  buildRapidDetailMesh,
  rapidDetailRandom,
  type RapidDetailCollider,
  type RapidDetailField,
  type RapidDetailMesh,
  type RapidDetailReachInput,
  type RapidDetailRock,
  type RapidDetailStoneFamily,
} from './rapid-detail';
export {
  VehicleWaterEvidence,
  type VehicleWaterAuthority,
  type VehicleWaterEvidenceInput,
  type VehicleWaterEvidenceSnapshot,
  type VehicleWaterStamp,
  type VehicleWaterStampKind,
  type VehicleWaterWheelSample,
} from './vehicle-water';
export * from './types';
