import { strict as assert } from 'node:assert';
import * as THREE from 'three';
import { createWildlifeWire } from './wildlife-wire';

const mode = createWildlifeWire();
const lit = new THREE.MeshLambertMaterial({ flatShading: true, vertexColors: true });
const geometry = new THREE.BoxGeometry();
const herd = new THREE.InstancedMesh(geometry, lit, 4);
const streamed = new THREE.InstancedMesh(geometry, lit, 4);
herd.setColorAt(0, new THREE.Color(0xff3300));
const matrices = herd.instanceMatrix, colours = herd.instanceColor;
mode.apply(herd, true);
const wire = herd.material as unknown as THREE.MeshBasicMaterial;
assert(wire.isMeshBasicMaterial && wire.wireframe && wire.vertexColors);
assert.equal(lit.wireframe, false);
mode.apply(herd, true);
mode.apply(streamed, true);
assert.equal(herd.material, wire);
assert.equal(streamed.material, wire);
assert.equal(herd.geometry, geometry);
assert.equal(herd.instanceMatrix, matrices);
assert.equal(herd.instanceColor, colours);
mode.apply(herd, false);
assert.equal(herd.material, lit);
mode.apply(herd, true);
mode.dispose();
assert.equal(herd.material, lit);
assert.equal(streamed.material, lit);
geometry.dispose(); lit.dispose();
console.log('wildlife wire: instancing, colour, cache and restoration pass');
