// @ts-nocheck
import {MOTIFS,rng,row,advance,odds,step} from './rules';
const $=(id)=>document.getElementById(id),qs=new URLSearchParams(location.search);const preview=qs.has('preview');if(preview)document.body.classList.add('preview');
const symbols=['♥','♦','♣','♠'],colours=['#ca4438','#d6ad35','#4e8164','#3c559f'],pos=[[110,105],[330,105],[330,310],[110,310]];
let seed=Number(qs.get('seed'))||1941,board=[4,0,5,1],hand=[],pile=[],selected=-1,moves=0,current=0,stage=0,history=[],undo=[],running=false,finished=false,runNo=0,timer=0;let workshop=qs.get('mode')==='workshop';$('mode').value=workshop?'workshop':'challenge';
function init(){clearTimeout(timer);running=false;finished=false;runNo=0;board=[4,0,5,1];const r=rng(seed);pile=[];for(let bag=0;bag<13;bag++){const cards=Array.from({length:8},(_,i)=>i);for(let i=7;i>0;i--){const j=Math.floor(r()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}pile.push(...cards);}hand=pile.splice(0,5);moves=0;current=0;stage=0;history=[];undo=[];selected=-1;try{const data=JSON.parse(qs.get('table')||'null');if(data&&Array.isArray(data.b)&&data.b.length===4&&data.b.every(x=>Number.isInteger(x)&&x>=0&&x<8)&&Array.isArray(data.h)&&data.h.length===5&&data.h.every(x=>Number.isInteger(x)&&x>=0&&x<8)&&Number.isInteger(data.m)&&data.m>=0&&data.m<=4){board=data.b;hand=data.h;moves=data.m;pile.splice(0,data.m);}}catch{}draw();}
function miniature(m){let lines='';row(m,0).forEach((p,d)=>{if(!p)return;const [x,y]=[[38,33],[65,58],[38,83],[11,58]][d];lines+=`<path d="M38 58 L${x} ${y}" stroke="#34312c" stroke-width="${1+p*3}"/><circle cx="${x}" cy="${y}" r="8" fill="${colours[d]}"/><text x="${x}" y="${y+3}" text-anchor="middle" fill="white" font-size="8">${p*4}</text>`;});return `<svg viewBox="0 0 76 110" aria-hidden="true"><text x="5" y="13" font-family="Georgia" font-size="13">${m+1}</text>${lines}<circle cx="38" cy="58" r="6" fill="#eee9d8" stroke="#34312c"/><text x="70" y="104" text-anchor="end" font-size="13">${m+1}</text></svg>`;}
function graph(){let html='<defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#403e37"/></marker></defs>';board.forEach((m,s)=>row(m,s).forEach((p,d)=>{if(!p)return;const [x,y]=pos[s],[xx,yy]=pos[d];if(d===s){html+=`<path class="edge" stroke-dasharray="2 5" d="M${x-26} ${y-26} C${x-90} ${y-110},${x+90} ${y-110},${x+26} ${y-26}" marker-end="url(#arrow)"/><text class="prob" x="${x}" y="${y-66}" text-anchor="middle">${p*100}%</text>`;}else{const dx=xx-x,dy=yy-y,len=Math.hypot(dx,dy),nx=-dy/len,ny=dx/len,bend=18;const ax=x+dx/len*36,ay=y+dy/len*36,bx=xx-dx/len*41,by=yy-dy/len*41,cx=(x+xx)/2+nx*bend,cy=(y+yy)/2+ny*bend;html+=`<path class="edge" opacity=".65" d="M${ax} ${ay} Q${cx} ${cy} ${bx} ${by}" marker-end="url(#arrow)"/><text class="prob" x="${cx+nx*7}" y="${cy+ny*7}" text-anchor="middle">${p*100}%</text>`;}}));pos.forEach(([x,y],s)=>{html+=`<g class="node" tabindex="0" role="button" aria-label="${symbols[s]} state, ${MOTIFS[board[s]].name}; place selected card here" data-state="${s}"><circle cx="${x}" cy="${y}" r="34" fill="${colours[s]}" stroke="#292720" stroke-width="2"/><text x="${x}" y="${y+12}" text-anchor="middle" fill="#faf5dd" font-size="34">${symbols[s]}</text><text x="${x}" y="${y+53}" text-anchor="middle" font-size="10" font-family="monospace">${MOTIFS[board[s]].name}</text>${s===current?`<circle cx="${x}" cy="${y}" r="41" fill="none" stroke="#2635a2" stroke-width="3" stroke-dasharray="4 3"/>`:''}</g>`;});$('graph').innerHTML=html;$('graph').querySelectorAll('[data-state]').forEach(el=>{el.onclick=()=>place(Number(el.dataset.state));el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();place(Number(el.dataset.state));}};});}
function draw(){graph();const chance=odds(board);$('odds').textContent=(chance<1?Math.min(99.9,chance*100).toFixed(1):'100.0')+'%';$('bar').style.width=chance*100+'%';$('deal').textContent=`DEAL ${seed} / ${workshop?'OPEN TABLE':`${4-moves} PLACEMENTS LEFT`}`;$('hand').innerHTML=hand.map((m,i)=>`<button class="card ${selected===i?'chosen':''}" data-card="${i}" aria-pressed="${selected===i}" aria-label="${MOTIFS[m].name}: ${MOTIFS[m].note}" ${running||finished&&!workshop?'disabled':''}>${miniature(m)}<span>${MOTIFS[m].name}</span></button>`).join('');$('hand').querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{selected=Number(el.dataset.card);draw();});$('detail').textContent=selected<0?'Select a card, then touch a state to change its routes.':MOTIFS[hand[selected]].name+' / '+MOTIFS[hand[selected]].note+' Touch a state to place it.';$('history').innerHTML=history.map(s=>`<span class="stamp" style="color:${colours[s]}">${symbols[s]}</span>`).join('');$('status').textContent=running?`Transition ${history.length-1}/8 · ${stage===0?'seeking ♣':'♣ visited · seeking ♦'}`:finished?(stage===2?'ARRIVED / ♣ then ♦. The chain carried you through.':'STRANDED / eight transitions passed. The commission is incomplete.'):`${workshop?'Workshop: place freely and repeat journeys.':'Plan the journey. Four placements; release when ready.'}`;$('run').disabled=running||finished&&!workshop;$('undo').disabled=running||finished&&!workshop||!undo.length;}
function place(s){if(selected<0||running||finished&&!workshop||!workshop&&moves>=4){if(!running&&!finished&&selected<0)$('status').textContent='Choose a card from your hand first.';return;}undo.push({board:[...board],hand:[...hand],pile:[...pile],moves});board[s]=hand[selected];hand[selected]=pile.shift()??0;moves++;selected=-1;draw();}
$('undo').onclick=()=>{const v=undo.pop();if(!v)return;({board,hand,pile,moves}=v);selected=-1;draw();};
$('run').onclick=()=>{if(running||finished&&!workshop)return;running=true;finished=false;current=0;stage=0;history=[0];selected=-1;const random=rng(seed^0x51ab^(workshop?runNo++:0));const tick=()=>{if(history.length>8||stage===2){running=false;finished=true;draw();return;}current=step(board,current,random);stage=advance(stage,current);history.push(current);draw();timer=setTimeout(tick,750);};draw();timer=setTimeout(tick,650);};
$('reset').onclick=()=>{qs.delete('table');const u=new URL(location.href);u.searchParams.delete('table');historyReplace(u);init();};$('new').onclick=()=>{seed++;qs.delete('table');init();const u=new URL(location.href);u.searchParams.set('seed',String(seed));u.searchParams.delete('table');historyReplace(u);};function historyReplace(u){window.history.replaceState(null,'',u);}
$('mode').onchange=()=>{workshop=$('mode').value==='workshop';qs.delete('table');const u=new URL(location.href);u.searchParams.set('mode',workshop?'workshop':'challenge');u.searchParams.delete('table');historyReplace(u);init();};
$('share').onclick=async()=>{const u=new URL(location.href);u.searchParams.delete('preview');u.searchParams.set('seed',String(seed));u.searchParams.set('mode',workshop?'workshop':'challenge');u.searchParams.set('table',JSON.stringify({b:board,h:hand,m:Math.min(4,moves)}));try{await navigator.clipboard.writeText(u.href);$('share-status').textContent='Table link copied.';}catch{const input=document.createElement('input');input.value=u.href;input.style.width='100%';$('share-status').replaceChildren(input);input.select();}};
init();if(preview){board=[6,1,7,2];draw();}
(window as any).__markovs={probe:()=>({seed,board:[...board],hand:[...hand],moves,odds:odds(board),running,finished,stage,history:[...history]})};
