// @ts-nocheck
import bootPhysical from './physical';
import bootTable from './page';
import archiveMarkup from './archive';
import {MOTIFS,rng,row,advance,odds,step,raceOdds,botMove} from './rules';

const entryMode=new URLSearchParams(location.search).get('mode');
if(!entryMode){bootTable();}else if(entryMode==='physical'){bootPhysical();}else{archiveMarkup();
const $=(id)=>document.getElementById(id),qs=new URLSearchParams(location.search);const preview=qs.has('preview');if(preview)document.body.classList.add('preview');
const symbols=['♥','♦','♣','♠'],colours=['#ca4438','#d6ad35','#4e8164','#3c559f'],pos=[[110,105],[330,105],[330,310],[110,310]];
let seed=Number(qs.get('seed'))||1941,board=[4,0,5,1],hand=[],pile=[],selected=-1,moves=0,current=0,stage=0,history=[],undo=[],running=false,finished=false,runNo=0,timer=0;let duel=qs.get('mode')==='duel',round=0,botHand=[],pending=false,botNote='',duelResult='';let workshop=qs.get('mode')==='workshop';$('mode').value=duel?'duel':workshop?'workshop':'challenge';
function init(){clearTimeout(timer);running=false;finished=false;runNo=0;board=[4,0,5,1];const r=rng(seed);pile=[];for(let bag=0;bag<13;bag++){const cards=Array.from({length:8},(_,i)=>i);for(let i=7;i>0;i--){const j=Math.floor(r()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]];}pile.push(...cards);}hand=pile.splice(0,5);botHand=duel?pile.splice(0,3):[];round=0;pending=false;botNote='';duelResult='';moves=0;current=0;stage=0;history=[];undo=[];selected=-1;try{const data=JSON.parse(qs.get('table')||'null');if(data&&Array.isArray(data.b)&&data.b.length===4&&data.b.every(x=>Number.isInteger(x)&&x>=0&&x<8)&&Array.isArray(data.h)&&data.h.length===5&&data.h.every(x=>Number.isInteger(x)&&x>=0&&x<8)&&Number.isInteger(data.m)&&data.m>=0&&data.m<=4){board=data.b;hand=data.h;moves=data.m;pile.splice(0,data.m);}}catch{}draw();}
function miniature(m){let lines='';row(m,0).forEach((p,d)=>{if(!p)return;const [x,y]=[[38,33],[65,58],[38,83],[11,58]][d];lines+=`<path d="M38 58 L${x} ${y}" stroke="#34312c" stroke-width="${1+p*3}"/><circle cx="${x}" cy="${y}" r="8" fill="#56554f"/><text x="${x}" y="${y+3}" text-anchor="middle" fill="white" font-size="8">${p*4}</text><text x="${x}" y="${y+15}" text-anchor="middle" font-size="5" fill="#333">${['STAY','CW','ACROSS','BACK'][d]}</text>`;});return `<svg viewBox="0 0 76 110" aria-hidden="true"><text x="5" y="13" font-family="Georgia" font-size="13">${m+1}</text>${lines}<circle cx="38" cy="58" r="6" fill="#eee9d8" stroke="#34312c"/><text x="70" y="104" text-anchor="end" font-size="13">${m+1}</text></svg>`;}
function graph(){let html='<defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#403e37"/></marker></defs>';board.forEach((m,s)=>row(m,s).forEach((p,d)=>{if(!p)return;const [x,y]=pos[s],[xx,yy]=pos[d];if(d===s){html+=`<path class="edge" stroke-dasharray="2 5" d="M${x-26} ${y-26} C${x-90} ${y-110},${x+90} ${y-110},${x+26} ${y-26}" marker-end="url(#arrow)"/><text class="prob" x="${x}" y="${y-66}" text-anchor="middle">${p*100}%</text>`;}else{const dx=xx-x,dy=yy-y,len=Math.hypot(dx,dy),nx=-dy/len,ny=dx/len,bend=18;const ax=x+dx/len*36,ay=y+dy/len*36,bx=xx-dx/len*41,by=yy-dy/len*41,cx=(x+xx)/2+nx*bend,cy=(y+yy)/2+ny*bend;html+=`<path class="edge" opacity=".65" d="M${ax} ${ay} Q${cx} ${cy} ${bx} ${by}" marker-end="url(#arrow)"/><text class="prob" x="${cx+nx*7}" y="${cy+ny*7}" text-anchor="middle">${p*100}%</text>`;}}));pos.forEach(([x,y],s)=>{html+=`<g class="node" tabindex="0" role="button" aria-label="${symbols[s]} state, ${MOTIFS[board[s]].name}; place selected card here" data-state="${s}"><circle cx="${x}" cy="${y}" r="34" fill="${colours[s]}" stroke="#292720" stroke-width="2"/><text x="${x}" y="${y+12}" text-anchor="middle" fill="#faf5dd" font-size="34">${symbols[s]}</text><text x="${x}" y="${y+53}" text-anchor="middle" font-size="10" font-family="monospace">${MOTIFS[board[s]].name}</text>${s===current?`<circle cx="${x}" cy="${y}" r="41" fill="none" stroke="#2635a2" stroke-width="3" stroke-dasharray="4 3"/>`:''}</g>`;});$('graph').innerHTML=html;$('graph').querySelectorAll('[data-state]').forEach(el=>{el.onclick=()=>place(Number(el.dataset.state));el.onpointerenter=()=>previewState(Number(el.dataset.state));el.onpointerleave=()=>{$('preview-note').textContent='';};el.onfocus=()=>previewState(Number(el.dataset.state));el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();place(Number(el.dataset.state));}};});}
function draw(){$('preview-note').textContent='';graph();const chance=duel?raceOdds(board,current,8-round).you:odds(board);$('odds').textContent=(chance<1?Math.min(99.9,chance*100).toFixed(1):'100.0')+'%';$('bar').style.width=chance*100+'%';$('forecast-note').textContent=duel?'Your chance of winning if these routes stay fixed for the remaining turns. Future placements can change it.':'Exact chance for the network on the table. A favourable chance is still a gamble.';$('bot-panel').hidden=!duel;$('commission').innerHTML=duel?'You seek <strong>♣</strong>. The bot seeks <strong>♠</strong>.<br>First arrival wins. Eight turns; one placement each per turn.':'Start at <b>♥</b>. Visit <strong>♣</strong>, then <strong>♦</strong>.<br>You have <b>8 transitions</b> and <b>4 card placements</b>';$('bot-panel').textContent='BOT HAND / '+botHand.map(m=>MOTIFS[m].name).join(' · ')+(botNote?' / '+botNote:'');$('run').textContent=duel?'commit turn →':'release the token →';$('deal').textContent=`DEAL ${seed} / ${duel?`TURN ${Math.min(8,round+1)}/8`:workshop?'OPEN TABLE':`${4-moves} PLACEMENTS LEFT`}`;$('hand').innerHTML=hand.map((m,i)=>`<button class="card ${selected===i?'chosen':''}" data-card="${i}" aria-pressed="${selected===i}" aria-label="${MOTIFS[m].name}: ${MOTIFS[m].note}" ${running||finished&&!workshop||duel&&pending?'disabled':''}>${miniature(m)}<span>${MOTIFS[m].name}</span></button>`).join('');$('hand').querySelectorAll('[data-card]').forEach(el=>el.onclick=()=>{selected=Number(el.dataset.card);draw();});$('detail').textContent=selected<0?'Select a card, then touch a state to change its routes.':MOTIFS[hand[selected]].name+' / '+MOTIFS[hand[selected]].note+' Touch a state to place it.';$('history').innerHTML=history.map(s=>`<span class="stamp" style="color:${colours[s]}">${symbols[s]}</span>`).join('');$('status').textContent=running?`Transition ${history.length-1}/8 · ${stage===0?'seeking ♣':'♣ visited · seeking ♦'}`:finished?(stage===2?'ARRIVED / ♣ then ♦. The chain carried you through.':'STRANDED / eight transitions passed. The commission is incomplete.'):`${workshop?'Workshop: place freely and repeat journeys.':'Plan the journey. Four placements; release when ready.'}`;if(duel)$('status').textContent=finished?duelResult:running?'Bot choosing, then the token moves…':pending?'Placement ready. Commit the turn, or undo.':'Your turn: choose a card, then a state.';$('run').disabled=running||finished&&!workshop||duel&&!pending;$('undo').disabled=running||finished&&!workshop||!undo.length;}
function place(s){if(selected<0||running||finished&&!workshop||(!workshop&&!duel&&moves>=4)||duel&&pending){if(!running&&!finished&&selected<0)$('status').textContent='Choose a card from your hand first.';return;}undo.push({board:[...board],hand:[...hand],pile:[...pile],moves});board[s]=hand[selected];hand[selected]=pile.shift()??0;moves++;if(duel)pending=true;selected=-1;draw();}
$('undo').onclick=()=>{const v=undo.pop();if(!v)return;({board,hand,pile,moves}=v);pending=false;selected=-1;draw();};
$('run').onclick=()=>{if(duel){duelTurn();return;}if(running||finished&&!workshop)return;running=true;finished=false;current=0;stage=0;history=[0];selected=-1;const random=rng(seed^0x51ab^(workshop?runNo++:0));const tick=()=>{if(history.length>8||stage===2){running=false;finished=true;draw();return;}current=step(board,current,random);stage=advance(stage,current);history.push(current);draw();timer=setTimeout(tick,750);};draw();timer=setTimeout(tick,650);};
$('reset').onclick=()=>{qs.delete('table');const u=new URL(location.href);u.searchParams.delete('table');historyReplace(u);init();};$('new').onclick=()=>{seed++;qs.delete('table');init();const u=new URL(location.href);u.searchParams.set('seed',String(seed));u.searchParams.delete('table');historyReplace(u);};function historyReplace(u){window.history.replaceState(null,'',u);}
$('mode').onchange=()=>{duel=$('mode').value==='duel';workshop=$('mode').value==='workshop';qs.delete('table');const u=new URL(location.href);u.searchParams.set('mode',duel?'duel':workshop?'workshop':'challenge');u.searchParams.delete('table');historyReplace(u);init();};
$('share').onclick=async()=>{if(duel){$('share-status').textContent='Duel sharing is not available yet; share a challenge or workshop table.';return;}const u=new URL(location.href);u.searchParams.delete('preview');u.searchParams.set('seed',String(seed));u.searchParams.set('mode',duel?'duel':workshop?'workshop':'challenge');u.searchParams.set('table',JSON.stringify({b:board,h:hand,m:Math.min(4,moves)}));try{await navigator.clipboard.writeText(u.href);$('share-status').textContent='Table link copied.';}catch{const input=document.createElement('input');input.value=u.href;input.style.width='100%';$('share-status').replaceChildren(input);input.select();}};
function previewState(s){if(selected<0)return;const routes=row(hand[selected],s).map((p,d)=>p?`${Math.round(p*100)}% → ${symbols[d]}`:'').filter(Boolean).join(' · ');$('preview-note').textContent=`At ${symbols[s]}: ${routes}`;}
function duelTurn(){if(!pending||running||finished)return;running=true;selected=-1;draw();timer=setTimeout(()=>{const pick=botMove(board,botHand,current,8-round),m=botHand[pick.card];board[pick.state]=m;botHand[pick.card]=pile.shift()??0;botNote=`placed ${MOTIFS[m].name} at ${symbols[pick.state]}`;draw();timer=setTimeout(()=>{current=step(board,current,rng(seed^((round+1)*0x51ab)));history.push(current);round++;pending=false;undo=[];running=false;if(current===2||current===3||round>=8){finished=true;duelResult=current===2?'YOU ARRIVED / ♣. You win.':current===3?'BOT ARRIVED / ♠. The bot wins.':'DRAW / neither destination reached in eight turns.';}draw();},900);},600);}
init();if(preview){board=[6,1,7,2];draw();}
(window as any).__markovs={probe:()=>({seed,board:[...board],hand:[...hand],moves,odds:odds(board),running,finished,stage,history:[...history]})};
// Guided small table, separate from the player's deal. Each beat requires an action.
let lessonStep=0,lessonCount=0,lessonSelected=false,lessonPlaced=false,lessonAt=0,lessonRunning=false,lessonTimer=0;
const lesson=$('lesson'),lessonRandom=rng(807);
function seen(){try{localStorage.setItem('markovs.learned.v1','yes');}catch{}}
function closeLesson(){clearTimeout(lessonTimer);lessonRunning=false;lesson.close();seen();}
function lessonGraph(){const three=lessonStep>=2,locations=three?[[65,95],[225,95],[385,95]]:[[100,95],[340,95]],suits=three?['♥','♣','♦']:['♥','♦'];let g='<defs><marker id="la" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#34312c"/></marker></defs>';
if(lessonStep===0)g+='<path d="M133 95H300" stroke="#333" marker-end="url(#la)"/><text x="220" y="72" text-anchor="middle">always</text>';
if(lessonStep===1)g+='<path d="M133 95H300" stroke="#333" marker-end="url(#la)"/><text x="220" y="72" text-anchor="middle">3 chances in 4</text><path d="M80 66C15 5 185 5 120 66" fill="none" stroke="#333" stroke-dasharray="3 5" marker-end="url(#la)"/><text x="100" y="24" text-anchor="middle">1 chance: stay</text>';
if(three){[65,225].forEach((x,i)=>{g+=`<path d="M${x-20} 66C${x-65} 5 ${x+65} 5 ${x+20} 66" fill="none" stroke="#333" stroke-dasharray="3 5" marker-end="url(#la)"/><text x="${x}" y="24" text-anchor="middle">${i===0&&!lessonPlaced?'75%':'25%'} stay</text>`;});g+=`<path d="M98 95H190" stroke="#333" marker-end="url(#la)"/><path d="M258 95H350" stroke="#333" marker-end="url(#la)"/><text x="145" y="68" text-anchor="middle">${lessonPlaced?'75%':'25%'}</text><text x="305" y="68" text-anchor="middle">75%</text><text x="65" y="163" text-anchor="middle">${lessonPlaced?'BRIDGE':'BEFORE'}</text>`;}
locations.forEach(([x,y],i)=>{const target=lessonStep===2&&lessonSelected&&i===0;g+=`<g ${target?'role="button" tabindex="0" aria-label="Place Bridge at hearts" id="lesson-place"':''}><circle cx="${x}" cy="${y}" r="32" fill="${three?[colours[0],colours[2],colours[1]][i]:colours[i]}" stroke="#28261d" stroke-width="2"/><text x="${x}" y="${y+10}" text-anchor="middle" fill="white" font-size="32">${suits[i]}</text>${lessonAt===i?`<circle cx="${x}" cy="${y}" r="39" fill="none" stroke="#27379b" stroke-width="3"/>`:''}${target?`<text x="${x}" y="193" text-anchor="middle" font-size="12">tap here</text>`:''}</g>`;});$('lesson-graph').innerHTML=g;const place=$('lesson-place');if(place){place.onclick=()=>{lessonPlaced=true;lessonSelected=false;$('lesson-result').textContent='Placed. Now three chances in four lead from ♥ to ♣.';renderLesson();};place.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();place.onclick();}};}}
function renderLesson(){lessonGraph();$('lesson-progress').textContent=`LEARN BY PLAYING / ${lessonStep+1} OF 4`;$('lesson-back').disabled=lessonStep===0||lessonRunning;const titles=['Follow an arrow','A loop spends a move','A card changes the routes','Give the journey a purpose'];const copy=['The blue ring is your token. It is at ♥. An arrow says where it can go next. Here there is only one route.','Now the token may move, or stay. Staying is a real transition too. Try at least three moves; chance need not produce an even pattern.','Choose BRIDGE, then tap ♥. A card changes the routes from where you put it. Card directions are relative: ACROSS means the opposite state on the full table. Here that is ♣.','Your small commission: reach ♣, then ♦, in three transitions. Release the token. A good route improves your chances; it does not promise success.'];$('lesson-title').textContent=titles[lessonStep];$('lesson-copy').textContent=copy[lessonStep];let controls='';if(lessonStep===0)controls='<button class="go" id="lesson-action">follow the arrow →</button>';if(lessonStep===1)controls='<button class="go" id="lesson-action">try one transition →</button>'+(lessonCount>=3?'<button id="lesson-next">now change the route →</button>':'');if(lessonStep===2)controls=lessonPlaced?'<button class="go" id="lesson-next">try a commission →</button>':'<button class="lesson-card '+(lessonSelected?'selected':'')+'" id="lesson-action">BRIDGE<br>3 parts ACROSS · 1 part STAY</button>';if(lessonStep===3)controls='<button class="go" id="lesson-action">release this journey →</button>'+(lessonCount?'<button id="lesson-finish">play the full table →</button><button id="lesson-duel">try the bot duel →</button>':'');$('lesson-controls').innerHTML=controls;const action=$('lesson-action');if(action){action.disabled=lessonRunning;action.onclick=lessonAction;}const next=$('lesson-next');if(next)next.onclick=()=>{lessonStep++;lessonCount=0;lessonAt=0;$('lesson-result').textContent='';renderLesson();};const finish=$('lesson-finish');if(finish)finish.onclick=()=>{closeLesson();};const bot=$('lesson-duel');if(bot)bot.onclick=()=>{closeLesson();duel=true;workshop=false;$('mode').value='duel';qs.delete('table');const u=new URL(location.href);u.searchParams.set('mode','duel');u.searchParams.delete('table');u.searchParams.delete('learn');historyReplace(u);init();};}
function lessonAction(){if(lessonStep===0){lessonAt=1;lessonGraph();$('lesson-result').textContent='The token reached ♦. One arrow, one transition.';$('lesson-controls').innerHTML='<button class="go" id="lesson-next">introduce chance →</button>';$('lesson-next').onclick=()=>{lessonStep=1;lessonAt=0;lessonCount=0;$('lesson-result').textContent='';renderLesson();};}else if(lessonStep===1){lessonAt=lessonRandom()<.75?1:0;lessonCount++;renderLesson();$('lesson-result').textContent=`Trial ${lessonCount}: ${lessonAt?'moved to ♦':'stayed at ♥'}. Each trial starts again at ♥.`;}else if(lessonStep===2){lessonSelected=true;renderLesson();$('lesson-result').textContent='Card selected. Touch the red ♥ state to place it.';}else{lessonRunning=true;lessonAt=0;let hops=0;renderLesson();$('lesson-result').textContent='The token begins at ♥.';const tick=()=>{hops++;if(lessonRandom()<.75)lessonAt++;lessonGraph();$('lesson-result').textContent=`Transition ${hops}/3 · ${['♥','♣','♦'][lessonAt]}`;if(lessonAt===2||hops===3){lessonRunning=false;lessonCount++;renderLesson();$('lesson-result').textContent=lessonAt===2?'Arrived: ♣, then ♦. Ready for the full table.':'Not this time. You can retry, or continue: uncertain outcomes are part of the game.';}else lessonTimer=setTimeout(tick,700);};lessonTimer=setTimeout(tick,700);}}
function openLesson(){if(running)return;lessonStep=0;lessonCount=0;lessonSelected=false;lessonPlaced=false;lessonAt=0;$('lesson-result').textContent='';renderLesson();lesson.showModal();}
$('learn').onclick=openLesson;$('lesson-skip').onclick=closeLesson;$('lesson-back').onclick=()=>{clearTimeout(lessonTimer);lessonRunning=false;lessonStep=Math.max(0,lessonStep-1);lessonCount=0;lessonAt=0;lessonSelected=false;lessonPlaced=lessonStep===3;$('lesson-result').textContent='';renderLesson();};lesson.addEventListener('cancel',()=>{clearTimeout(lessonTimer);lessonRunning=false;});
if(!preview&&!qs.has('mode')&&!qs.has('table')){let learned=false;try{learned=localStorage.getItem('markovs.learned.v1')==='yes';}catch{}if(!learned)openLesson();}if(qs.get('learn')==='1'&&!preview&&!lesson.open)openLesson();

}
