/* In-memory fs for the vendored playtest engine (generated by scripts/vendor-playtest.mjs).
 * Only the calls the engine makes. One game per page; the lab resets it. */
import { SEED_FILES } from './data';

const files = new Map<string, string>(Object.entries(SEED_FILES));
const dirs = new Set<string>(['/', '/pt']);

const norm = (p: string) => p.replace(/\/+/g, '/').replace(/\/$/, '') || '/';
const parentsOf = (p: string) => {
  const out: string[] = [];
  let cur = norm(p);
  while (cur.includes('/') && cur !== '/') {
    cur = cur.slice(0, cur.lastIndexOf('/')) || '/';
    out.push(cur);
  }
  return out;
};
function enoent(p: string): Error {
  return Object.assign(new Error(`ENOENT: no such file or directory, '${p}'`), { code: 'ENOENT' });
}

export function existsSync(p: string): boolean {
  const k = norm(p);
  return files.has(k) || dirs.has(k);
}
export function readFileSync(p: string, _enc?: unknown): string {
  const k = norm(p);
  const v = files.get(k);
  if (v === undefined) throw enoent(k);
  return v;
}
export function writeFileSync(p: string, data: string, opts?: { flag?: string } | string): void {
  const k = norm(p);
  if (typeof opts === 'object' && opts?.flag === 'wx' && files.has(k)) {
    throw Object.assign(new Error(`EEXIST: file already exists, '${k}'`), { code: 'EEXIST' });
  }
  files.set(k, String(data));
  parentsOf(k).forEach((d) => dirs.add(d));
}
export function appendFileSync(p: string, data: string): void {
  const k = norm(p);
  files.set(k, (files.get(k) ?? '') + String(data));
  parentsOf(k).forEach((d) => dirs.add(d));
}
export function mkdirSync(p: string, _opts?: unknown): void {
  const k = norm(p);
  dirs.add(k);
  parentsOf(k).forEach((d) => dirs.add(d));
}
export function unlinkSync(p: string): void {
  if (!files.delete(norm(p))) throw enoent(p);
}
export function readdirSync(p: string): string[] {
  const k = norm(p);
  if (!dirs.has(k)) throw enoent(k);
  const pre = k === '/' ? '/' : k + '/';
  const names = new Set<string>();
  for (const f of [...files.keys(), ...dirs]) {
    if (f.startsWith(pre) && f !== k) names.add(f.slice(pre.length).split('/')[0]);
  }
  return [...names].sort();
}
export function statSync(p: string): { isDirectory(): boolean; isFile(): boolean; mtimeMs: number } {
  const k = norm(p);
  if (!files.has(k) && !dirs.has(k)) throw enoent(k);
  const dir = dirs.has(k);
  return { isDirectory: () => dir, isFile: () => !dir, mtimeMs: 0 };
}
export function watch(): never {
  throw new Error('fs.watch is not available in the lab');
}
export type FSWatcher = never;

/** Lab-only: drop every game's state and logs (seed data stays). */
export function resetGames(): void {
  for (const k of [...files.keys()]) if (k.startsWith('/pt/games/')) files.delete(k);
  for (const d of [...dirs]) if (d.startsWith('/pt/games/')) dirs.delete(d);
}
/** Lab-only: read every file under a prefix (e.g. a game's logs). */
export function filesUnder(prefix: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of files) if (k.startsWith(prefix)) out[k] = v;
  return out;
}
export default { existsSync, readFileSync, writeFileSync, appendFileSync, mkdirSync, unlinkSync, readdirSync, statSync, watch };
